CREATE TABLE dataset_table (
    ID STRING NOT NULL,
    Library_ID STRING NOT NULL,
    Sub_ID_1 STRING NOT NULL,
    Sub_ID_2 STRING NOT NULL,
    Sub_ID_3 STRING,
    MW FLOAT64 NOT NULL,
    LogP FLOAT64 NOT NULL,
    FP ARRAY<FLOAT64> NOT NULL,
    FP1 STRING NOT NULL,
    FP2 STRING NOT NULL,
    FP3 STRING NOT NULL,
    FP4 STRING,
    FP5 STRING
)
PARTITION BY DATE(_PARTITIONDATE),
CLUSTER BY ID;